name: Build Hydrogen Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          submodules: false

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential bc git bison flex libssl-dev libncurses5-dev libelf-dev zip wget curl \
            gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi

          mkdir -p aosp-clang
          curl -Lo clang.tar.gz "https://github.com/ZyCromerZ/Clang/releases/download/14.0.6-20250704-release/Clang-14.0.6-20250704.tar.gz"
          tar -xzf clang.tar.gz -C aosp-clang
          rm clang.tar.gz

      - name: Compile Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64

          export PATH="$(pwd)/aosp-clang/bin:$PATH"

          export CC=clang
          export CLANG_TRIPLE=aarch64-linux-gnu-
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-

          make O=out pissarro_defconfig
          make -j$(nproc) O=out

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hydrogen-Test-Kernel
          path: out/arch/arm64/boot/
