name: Build Hydrogen Kernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4 # Обновлено до v4

      - name: Setup Build Environment
        run: |
          sudo apt update
          sudo apt install -y build-essential bc git bison flex libssl-dev libncurses5-dev libelf-dev zip
          # Скачиваем официальный Google Clang нужной версии напрямую, чтобы избежать проблем с Git
          wget https://googlesource.com
          mkdir clang-r563880c
          tar -xf clang-r563880c.tar.gz -C clang-r563880c
          
      - name: Compile Kernel
        run: |
          export ARCH=arm64
          export SUBARCH=arm64
          export PATH="$(pwd)/clang-r563880c/bin:$PATH"
          export CC=clang
          export CROSS_COMPILE=aarch64-linux-gnu-
          export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
          
          make O=out pissarro_defconfig
          make -j$(nproc) O=out

      - name: Upload Kernel Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Hydrogen-Test-Kernel
          path: out/arch/arm64/boot/
          
